"use client";

import { useActionState, useState } from "react";
import Link from "next/link";
import {
  Field,
  TextInput,
  TextArea,
  ColorInput,
  SectionHeader,
} from "@/components/form-primitives";
import { createClientAction, type CreateClientResult } from "@/app/(panel)/clients/_actions";
import { EMPTY_CLIENT } from "@/lib/client-schema";

const initialState: CreateClientResult | null = null;

export function AddClientForm() {
  const [state, formAction, isPending] = useActionState(
    createClientAction,
    initialState
  );

  const errors = state?.fieldErrors ?? {};
  const formError = state?.formError;

  // Local state just so the color chip labels update live as the user picks.
  const [colors, setColors] = useState(EMPTY_CLIENT.profile.brandColors);

  return (
    <form action={formAction} className="space-y-8">
      {/* ================ IDENTITY ================ */}
      <section className="space-y-4">
        <SectionHeader
          title="Identity"
          description="The basics — how the agent addresses the client and where to reach them."
        />
        <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
          <Field label="Business name" name="name" error={errors.name} required>
            <TextInput
              id="name"
              name="name"
              placeholder="Bambo Sushi"
              defaultValue={EMPTY_CLIENT.name}
              required
            />
          </Field>
          <Field
            label="Phone (international, digits only)"
            name="phone"
            error={errors.phone}
            hint="e.g. 212609228322 — drop the leading 0 and add the country code"
            required
          >
            <TextInput
              id="phone"
              name="phone"
              placeholder="212609228322"
              defaultValue={EMPTY_CLIENT.phone}
              required
              inputMode="numeric"
            />
          </Field>
          <Field
            label="Security PIN"
            name="pin"
            error={errors.pin}
            hint="4–6 digits. The owner types this after their first message."
            required
          >
            <TextInput
              id="pin"
              name="pin"
              defaultValue={EMPTY_CLIENT.pin}
              required
              inputMode="numeric"
            />
          </Field>
          <Field
            label="Business type"
            name="profile.businessType"
            error={errors["profile.businessType"]}
          >
            <TextInput
              id="profile.businessType"
              name="businessType"
              defaultValue={EMPTY_CLIENT.profile.businessType}
              placeholder="restaurant"
            />
          </Field>
        </div>
      </section>

      {/* ================ WORDPRESS ================ */}
      <section className="space-y-4">
        <SectionHeader
          title="WordPress"
          description="Credentials generated by the Intelligent Site Connector plugin on the client's site. The key and secret are encrypted before they touch the database."
        />
        <div className="grid grid-cols-1 gap-4">
          <Field
            label="WordPress URL"
            name="wordpressUrl"
            error={errors.wordpressUrl}
            hint="The public homepage URL of the client's WordPress site."
            required
          >
            <TextInput
              id="wordpressUrl"
              name="wordpressUrl"
              type="url"
              placeholder="https://example.com"
              defaultValue={EMPTY_CLIENT.wordpressUrl}
              required
            />
          </Field>
          <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
            <Field
              label="API key"
              name="wpApiKey"
              error={errors.wpApiKey}
              required
            >
              <TextInput
                id="wpApiKey"
                name="wpApiKey"
                type="password"
                defaultValue={EMPTY_CLIENT.wpApiKey}
                required
              />
            </Field>
            <Field
              label="API secret"
              name="wpApiSecret"
              error={errors.wpApiSecret}
              required
            >
              <TextInput
                id="wpApiSecret"
                name="wpApiSecret"
                type="password"
                defaultValue={EMPTY_CLIENT.wpApiSecret}
                required
              />
            </Field>
          </div>
        </div>
      </section>

      {/* ================ BRAND PROFILE ================ */}
      <section className="space-y-4">
        <SectionHeader
          title="Brand profile"
          description="What the AI agent needs to know about the business. Used both for WhatsApp responses and for any on-site chatbot generation."
        />
        <div className="grid grid-cols-1 gap-4">
          <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
            <Field
              label="Language"
              name="profile.language"
              error={errors["profile.language"]}
              required
            >
              <TextInput
                id="profile.language"
                name="language"
                defaultValue={EMPTY_CLIENT.profile.language}
                placeholder="English"
                required
              />
            </Field>
            <Field
              label="Tone"
              name="profile.tone"
              error={errors["profile.tone"]}
              required
            >
              <TextInput
                id="profile.tone"
                name="tone"
                defaultValue={EMPTY_CLIENT.profile.tone}
                required
              />
            </Field>
          </div>
          <Field
            label="Brand description"
            name="profile.brandDescription"
            error={errors["profile.brandDescription"]}
            hint="Who they are. Two or three sentences."
            required
          >
            <TextArea
              id="profile.brandDescription"
              name="brandDescription"
              rows={4}
              defaultValue={EMPTY_CLIENT.profile.brandDescription}
              placeholder="e.g. A refined Japanese omakase and sushi bar in Brooklyn, NY…"
              required
            />
          </Field>
          <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
            <Field
              label="What they sell"
              name="profile.whatTheySell"
              error={errors["profile.whatTheySell"]}
              required
            >
              <TextArea
                id="profile.whatTheySell"
                name="whatTheySell"
                rows={3}
                defaultValue={EMPTY_CLIENT.profile.whatTheySell}
                required
              />
            </Field>
            <Field
              label="Target audience"
              name="profile.targetAudience"
              error={errors["profile.targetAudience"]}
              required
            >
              <TextArea
                id="profile.targetAudience"
                name="targetAudience"
                rows={3}
                defaultValue={EMPTY_CLIENT.profile.targetAudience}
                required
              />
            </Field>
          </div>
          <Field
            label="Image style"
            name="profile.imageStyle"
            error={errors["profile.imageStyle"]}
            hint="Used when the agent generates images for the site."
            required
          >
            <TextArea
              id="profile.imageStyle"
              name="imageStyle"
              rows={3}
              defaultValue={EMPTY_CLIENT.profile.imageStyle}
              required
            />
          </Field>
          <Field
            label="Do not"
            name="profile.doNot"
            error={errors["profile.doNot"]}
            hint="Hard rules the agent must obey. Added straight into the system prompt."
            required
          >
            <TextArea
              id="profile.doNot"
              name="doNot"
              rows={3}
              defaultValue={EMPTY_CLIENT.profile.doNot}
              required
            />
          </Field>
        </div>
      </section>

      {/* ================ BRAND COLORS ================ */}
      <section className="space-y-4">
        <SectionHeader
          title="Brand colors"
          description="Used in generated imagery and site theming."
        />
        <div className="grid grid-cols-2 gap-4 md:grid-cols-4">
          {(
            ["primary", "secondary", "accent", "background"] as const
          ).map((key) => (
            <Field
              key={key}
              label={key.charAt(0).toUpperCase() + key.slice(1)}
              name={`profile.brandColors.${key}`}
              error={errors[`profile.brandColors.${key}`]}
            >
              <ColorInput
                name={`brandColors.${key}`}
                value={colors[key]}
                onChange={(e) =>
                  setColors({ ...colors, [key]: e.target.value })
                }
              />
            </Field>
          ))}
        </div>
      </section>

      {/* ================ FOOTER / SUBMIT ================ */}
      {formError && (
        <div className="rounded-md border border-destructive bg-destructive/5 p-3 text-sm text-destructive">
          {formError}
        </div>
      )}
      <div className="flex items-center justify-end gap-3 border-t pt-4">
        <Link
          href="/clients"
          className="inline-flex h-9 items-center justify-center rounded-md border px-4 text-sm font-medium transition-colors hover:bg-muted"
        >
          Cancel
        </Link>
        <button
          type="submit"
          disabled={isPending}
          className="inline-flex h-9 items-center justify-center rounded-md bg-primary px-4 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 disabled:opacity-50"
        >
          {isPending ? "Creating…" : "Create client"}
        </button>
      </div>
    </form>
  );
}
